import time


def get_numbs(count: int, gen):
    '''Return a given number of numbers generated by given generator as list'''
    n = 0
    listed_nums = []
    while n < count:
        num = next(gen)
        listed_nums.append(num)
        n += 1
    return listed_nums


def fib_gen():
    '''Generate fibonacci numbers in sequence'''
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b


def prime_gen():
    '''Generate prime numbers in sequence'''
    n = 2
    while True:
        is_prime = True
        div = n - 1
        while div > 1:
            if n % div == 0:
                is_prime = False
                break
            div -= 1
        if is_prime == True:
            yield n
        n += 1


def events_gen(players: list, events: list, event_count: int):
    '''Generate game events'''
    for i in range(event_count):
        player, level = players[i % len(players)]
        event = events[i % len(events)]
        yield [player, level, event]


if __name__ == "__main__":
    players = [('alice', 5), ('bob', 12), ('charlie', 8), ('neva', 4)]
    events = ['killed a monster', 'found treasure',
              'leveled up', 'crafted an orb']

    event_count = 1000
    high_level_players = 0
    treasure_events = 0
    level_up = 0

    print("=== Game Data Stream Processor ===\n")

    print(f"Processing {event_count} game events...")
    start_time = time.time()
    event_stream = events_gen(players, events, event_count)

    n = 0
    for data in event_stream:
        player = data[0]
        level = data[1]
        event = data[2]

        if n < 3:
            print(f"Event {n + 1}: Player {player} (level {level}) {event}")
        elif n == 3:
            print("...")
        if level >= 10:
            high_level_players += 1
        n += 1
        if event == "found treasure":
            treasure_events += 1
        elif event == "leveled up":
            level_up += 1

    end_time = time.time()

    print("\n=== Stream Analytics ===")
    print(f"Total events processed: {event_count}")
    print(f"High-level players (10+): {high_level_players}")
    print(f"Treasure events: {treasure_events}")
    print(f"Level-up events: {level_up}")

    print("\nMemory usage: Constant (streaming)")
    print(f"Processing time: {end_time - start_time:.3f} seconds")

    print("\n=== Generator Demonstration ===")
    fib_list = get_numbs(10, fib_gen())
    fib_str = ", ".join([str(n) for n in fib_list])
    prime_nums = get_numbs(5, prime_gen())
    prime_str = ", ".join([str(n) for n in prime_nums])
    print(f"Fibonacci sequence (first 10): {fib_str}")
    print(f"Prime numbers (first 5): {prime_str}")
